---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ssd

