apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-share
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.1.4.39
    path: /mnt/nfs
