apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-share
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.2
    path: /VOLUME01
