---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  volumeName: gitlab-share
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
